### PR TITLE
feat: package extension yamls

### PR DESCRIPTION
**Pull request by gforsyth**
Include the extension yaml files in the Python package so that downstream 
projects can open and parse the bundled extension definitions as needed.

### CODE REVIEW

**Comment by gforsyth** [comment]
This is built on top of #14 -- I'll rebase it once that's in.

**Comment by gforsyth** [comment]
cc @danepitkin @jorisvandenbossche

**Comment by danepitkin** [comment]
LGTM! 🎉

**Review by richtia — APPROVED** [review]
Looks good! Thanks for taking care of this!

**Pull request merged**
